export type Country = { code: string; name_ar: string; name_en: string };

export const COUNTRIES: Country[] = [
  { code: "SA", name_ar: "المملكة العربية السعودية", name_en: "Saudi Arabia" },
  { code: "AE", name_ar: "الإمارات العربية المتحدة", name_en: "United Arab Emirates" },
  { code: "EG", name_ar: "مصر", name_en: "Egypt" },
  { code: "KW", name_ar: "الكويت", name_en: "Kuwait" },
  { code: "QA", name_ar: "قطر", name_en: "Qatar" },
  { code: "BH", name_ar: "البحرين", name_en: "Bahrain" },
  { code: "OM", name_ar: "عُمان", name_en: "Oman" },
  { code: "JO", name_ar: "الأردن", name_en: "Jordan" },
  { code: "LB", name_ar: "لبنان", name_en: "Lebanon" },
  { code: "SY", name_ar: "سوريا", name_en: "Syria" },
  { code: "IQ", name_ar: "العراق", name_en: "Iraq" },
  { code: "YE", name_ar: "اليمن", name_en: "Yemen" },
  { code: "PS", name_ar: "فلسطين", name_en: "Palestine" },
  { code: "LY", name_ar: "ليبيا", name_en: "Libya" },
  { code: "TN", name_ar: "تونس", name_en: "Tunisia" },
  { code: "DZ", name_ar: "الجزائر", name_en: "Algeria" },
  { code: "MA", name_ar: "المغرب", name_en: "Morocco" },
  { code: "SD", name_ar: "السودان", name_en: "Sudan" },
  { code: "SO", name_ar: "الصومال", name_en: "Somalia" },
  { code: "DJ", name_ar: "جيبوتي", name_en: "Djibouti" },
  { code: "MR", name_ar: "موريتانيا", name_en: "Mauritania" },
  { code: "KM", name_ar: "جزر القمر", name_en: "Comoros" },
  { code: "TR", name_ar: "تركيا", name_en: "Turkey" },
  { code: "IR", name_ar: "إيران", name_en: "Iran" },
  { code: "PK", name_ar: "باكستان", name_en: "Pakistan" },
  { code: "AF", name_ar: "أفغانستان", name_en: "Afghanistan" },
  { code: "IN", name_ar: "الهند", name_en: "India" },
  { code: "BD", name_ar: "بنغلاديش", name_en: "Bangladesh" },
  { code: "LK", name_ar: "سريلانكا", name_en: "Sri Lanka" },
  { code: "NP", name_ar: "نيبال", name_en: "Nepal" },
  { code: "BT", name_ar: "بوتان", name_en: "Bhutan" },
  { code: "MV", name_ar: "جزر المالديف", name_en: "Maldives" },
  { code: "CN", name_ar: "الصين", name_en: "China" },
  { code: "JP", name_ar: "اليابان", name_en: "Japan" },
  { code: "KR", name_ar: "كوريا الجنوبية", name_en: "South Korea" },
  { code: "KP", name_ar: "كوريا الشمالية", name_en: "North Korea" },
  { code: "MN", name_ar: "منغوليا", name_en: "Mongolia" },
  { code: "VN", name_ar: "فيتنام", name_en: "Vietnam" },
  { code: "TH", name_ar: "تايلاند", name_en: "Thailand" },
  { code: "MM", name_ar: "ميانمار", name_en: "Myanmar" },
  { code: "LA", name_ar: "لاوس", name_en: "Laos" },
  { code: "KH", name_ar: "كمبوديا", name_en: "Cambodia" },
  { code: "MY", name_ar: "ماليزيا", name_en: "Malaysia" },
  { code: "SG", name_ar: "سنغافورة", name_en: "Singapore" },
  { code: "ID", name_ar: "إندونيسيا", name_en: "Indonesia" },
  { code: "PH", name_ar: "الفلبين", name_en: "Philippines" },
  { code: "BN", name_ar: "بروناي", name_en: "Brunei" },
  { code: "TL", name_ar: "تيمور الشرقية", name_en: "Timor-Leste" },
  { code: "TW", name_ar: "تايوان", name_en: "Taiwan" },
  { code: "HK", name_ar: "هونغ كونغ", name_en: "Hong Kong" },
  { code: "MO", name_ar: "ماكاو", name_en: "Macau" },
  { code: "KZ", name_ar: "كازاخستان", name_en: "Kazakhstan" },
  { code: "UZ", name_ar: "أوزبكستان", name_en: "Uzbekistan" },
  { code: "TM", name_ar: "تركمانستان", name_en: "Turkmenistan" },
  { code: "TJ", name_ar: "طاجيكستان", name_en: "Tajikistan" },
  { code: "KG", name_ar: "قيرغيزستان", name_en: "Kyrgyzstan" },
  { code: "AZ", name_ar: "أذربيجان", name_en: "Azerbaijan" },
  { code: "AM", name_ar: "أرمينيا", name_en: "Armenia" },
  { code: "GE", name_ar: "جورجيا", name_en: "Georgia" },
  { code: "RU", name_ar: "روسيا", name_en: "Russia" },
  { code: "UA", name_ar: "أوكرانيا", name_en: "Ukraine" },
  { code: "BY", name_ar: "بيلاروسيا", name_en: "Belarus" },
  { code: "MD", name_ar: "مولدوفا", name_en: "Moldova" },
  { code: "PL", name_ar: "بولندا", name_en: "Poland" },
  { code: "CZ", name_ar: "التشيك", name_en: "Czech Republic" },
  { code: "SK", name_ar: "سلوفاكيا", name_en: "Slovakia" },
  { code: "HU", name_ar: "المجر", name_en: "Hungary" },
  { code: "RO", name_ar: "رومانيا", name_en: "Romania" },
  { code: "BG", name_ar: "بلغاريا", name_en: "Bulgaria" },
  { code: "GR", name_ar: "اليونان", name_en: "Greece" },
  { code: "AL", name_ar: "ألبانيا", name_en: "Albania" },
  { code: "MK", name_ar: "مقدونيا الشمالية", name_en: "North Macedonia" },
  { code: "RS", name_ar: "صربيا", name_en: "Serbia" },
  { code: "ME", name_ar: "الجبل الأسود", name_en: "Montenegro" },
  { code: "BA", name_ar: "البوسنة والهرسك", name_en: "Bosnia and Herzegovina" },
  { code: "HR", name_ar: "كرواتيا", name_en: "Croatia" },
  { code: "SI", name_ar: "سلوفينيا", name_en: "Slovenia" },
  { code: "XK", name_ar: "كوسوفو", name_en: "Kosovo" },
  { code: "DE", name_ar: "ألمانيا", name_en: "Germany" },
  { code: "FR", name_ar: "فرنسا", name_en: "France" },
  { code: "GB", name_ar: "المملكة المتحدة", name_en: "United Kingdom" },
  { code: "IE", name_ar: "أيرلندا", name_en: "Ireland" },
  { code: "IT", name_ar: "إيطاليا", name_en: "Italy" },
  { code: "ES", name_ar: "إسبانيا", name_en: "Spain" },
  { code: "PT", name_ar: "البرتغال", name_en: "Portugal" },
  { code: "NL", name_ar: "هولندا", name_en: "Netherlands" },
  { code: "BE", name_ar: "بلجيكا", name_en: "Belgium" },
  { code: "LU", name_ar: "لوكسمبورغ", name_en: "Luxembourg" },
  { code: "CH", name_ar: "سويسرا", name_en: "Switzerland" },
  { code: "AT", name_ar: "النمسا", name_en: "Austria" },
  { code: "DK", name_ar: "الدنمارك", name_en: "Denmark" },
  { code: "SE", name_ar: "السويد", name_en: "Sweden" },
  { code: "NO", name_ar: "النرويج", name_en: "Norway" },
  { code: "FI", name_ar: "فنلندا", name_en: "Finland" },
  { code: "IS", name_ar: "آيسلندا", name_en: "Iceland" },
  { code: "EE", name_ar: "إستونيا", name_en: "Estonia" },
  { code: "LV", name_ar: "لاتفيا", name_en: "Latvia" },
  { code: "LT", name_ar: "ليتوانيا", name_en: "Lithuania" },
  { code: "MT", name_ar: "مالطا", name_en: "Malta" },
  { code: "CY", name_ar: "قبرص", name_en: "Cyprus" },
  { code: "AD", name_ar: "أندورا", name_en: "Andorra" },
  { code: "MC", name_ar: "موناكو", name_en: "Monaco" },
  { code: "LI", name_ar: "ليختنشتاين", name_en: "Liechtenstein" },
  { code: "SM", name_ar: "سان مارينو", name_en: "San Marino" },
  { code: "VA", name_ar: "الفاتيكان", name_en: "Vatican City" },
  { code: "US", name_ar: "الولايات المتحدة الأمريكية", name_en: "United States" },
  { code: "CA", name_ar: "كندا", name_en: "Canada" },
  { code: "MX", name_ar: "المكسيك", name_en: "Mexico" },
  { code: "BR", name_ar: "البرازيل", name_en: "Brazil" },
  { code: "AR", name_ar: "الأرجنتين", name_en: "Argentina" },
  { code: "CL", name_ar: "تشيلي", name_en: "Chile" },
  { code: "CO", name_ar: "كولومبيا", name_en: "Colombia" },
  { code: "PE", name_ar: "بيرو", name_en: "Peru" },
  { code: "VE", name_ar: "فنزويلا", name_en: "Venezuela" },
  { code: "EC", name_ar: "الإكوادور", name_en: "Ecuador" },
  { code: "BO", name_ar: "بوليفيا", name_en: "Bolivia" },
  { code: "PY", name_ar: "باراغواي", name_en: "Paraguay" },
  { code: "UY", name_ar: "أوروغواي", name_en: "Uruguay" },
  { code: "GY", name_ar: "غيانا", name_en: "Guyana" },
  { code: "SR", name_ar: "سورينام", name_en: "Suriname" },
  { code: "PA", name_ar: "بنما", name_en: "Panama" },
  { code: "CR", name_ar: "كوستاريكا", name_en: "Costa Rica" },
  { code: "NI", name_ar: "نيكاراغوا", name_en: "Nicaragua" },
  { code: "HN", name_ar: "هندوراس", name_en: "Honduras" },
  { code: "SV", name_ar: "السلفادور", name_en: "El Salvador" },
  { code: "GT", name_ar: "غواتيمالا", name_en: "Guatemala" },
  { code: "BZ", name_ar: "بليز", name_en: "Belize" },
  { code: "CU", name_ar: "كوبا", name_en: "Cuba" },
  { code: "JM", name_ar: "جامايكا", name_en: "Jamaica" },
  { code: "HT", name_ar: "هايتي", name_en: "Haiti" },
  { code: "DO", name_ar: "جمهورية الدومينيكان", name_en: "Dominican Republic" },
  { code: "TT", name_ar: "ترينيداد وتوباغو", name_en: "Trinidad and Tobago" },
  { code: "BS", name_ar: "جزر البهاما", name_en: "Bahamas" },
  { code: "BB", name_ar: "بربادوس", name_en: "Barbados" },
  { code: "ZA", name_ar: "جنوب أفريقيا", name_en: "South Africa" },
  { code: "NG", name_ar: "نيجيريا", name_en: "Nigeria" },
  { code: "KE", name_ar: "كينيا", name_en: "Kenya" },
  { code: "ET", name_ar: "إثيوبيا", name_en: "Ethiopia" },
  { code: "GH", name_ar: "غانا", name_en: "Ghana" },
  { code: "TZ", name_ar: "تنزانيا", name_en: "Tanzania" },
  { code: "UG", name_ar: "أوغندا", name_en: "Uganda" },
  { code: "DZ", name_ar: "الجزائر", name_en: "Algeria" },
  { code: "MZ", name_ar: "موزمبيق", name_en: "Mozambique" },
  { code: "MG", name_ar: "مدغشقر", name_en: "Madagascar" },
  { code: "CM", name_ar: "الكاميرون", name_en: "Cameroon" },
  { code: "CI", name_ar: "ساحل العاج", name_en: "Ivory Coast" },
  { code: "SN", name_ar: "السنغال", name_en: "Senegal" },
  { code: "ML", name_ar: "مالي", name_en: "Mali" },
  { code: "NE", name_ar: "النيجر", name_en: "Niger" },
  { code: "TD", name_ar: "تشاد", name_en: "Chad" },
  { code: "BF", name_ar: "بوركينا فاسو", name_en: "Burkina Faso" },
  { code: "RW", name_ar: "رواندا", name_en: "Rwanda" },
  { code: "BI", name_ar: "بوروندي", name_en: "Burundi" },
  { code: "ZM", name_ar: "زامبيا", name_en: "Zambia" },
  { code: "ZW", name_ar: "زيمبابوي", name_en: "Zimbabwe" },
  { code: "BW", name_ar: "بوتسوانا", name_en: "Botswana" },
  { code: "NA", name_ar: "ناميبيا", name_en: "Namibia" },
  { code: "AO", name_ar: "أنغولا", name_en: "Angola" },
  { code: "CD", name_ar: "جمهورية الكونغو الديمقراطية", name_en: "DR Congo" },
  { code: "CG", name_ar: "جمهورية الكونغو", name_en: "Congo" },
  { code: "GA", name_ar: "الغابون", name_en: "Gabon" },
  { code: "GQ", name_ar: "غينيا الاستوائية", name_en: "Equatorial Guinea" },
  { code: "GW", name_ar: "غينيا بيساو", name_en: "Guinea-Bissau" },
  { code: "GN", name_ar: "غينيا", name_en: "Guinea" },
  { code: "SL", name_ar: "سيراليون", name_en: "Sierra Leone" },
  { code: "LR", name_ar: "ليبيريا", name_en: "Liberia" },
  { code: "TG", name_ar: "توغو", name_en: "Togo" },
  { code: "BJ", name_ar: "بنين", name_en: "Benin" },
  { code: "MW", name_ar: "ملاوي", name_en: "Malawi" },
  { code: "LS", name_ar: "ليسوتو", name_en: "Lesotho" },
  { code: "SZ", name_ar: "إسواتيني", name_en: "Eswatini" },
  { code: "ER", name_ar: "إريتريا", name_en: "Eritrea" },
  { code: "SS", name_ar: "جنوب السودان", name_en: "South Sudan" },
  { code: "CV", name_ar: "الرأس الأخضر", name_en: "Cabo Verde" },
  { code: "ST", name_ar: "ساو تومي وبرينسيب", name_en: "Sao Tome and Principe" },
  { code: "SC", name_ar: "سيشل", name_en: "Seychelles" },
  { code: "MU", name_ar: "موريشيوس", name_en: "Mauritius" },
  { code: "AU", name_ar: "أستراليا", name_en: "Australia" },
  { code: "NZ", name_ar: "نيوزيلندا", name_en: "New Zealand" },
  { code: "FJ", name_ar: "فيجي", name_en: "Fiji" },
  { code: "PG", name_ar: "بابوا غينيا الجديدة", name_en: "Papua New Guinea" },
  { code: "SB", name_ar: "جزر سليمان", name_en: "Solomon Islands" },
  { code: "VU", name_ar: "فانواتو", name_en: "Vanuatu" },
  { code: "WS", name_ar: "ساموا", name_en: "Samoa" },
  { code: "TO", name_ar: "تونغا", name_en: "Tonga" },
  { code: "KI", name_ar: "كيريباتي", name_en: "Kiribati" },
  { code: "PW", name_ar: "بالاو", name_en: "Palau" },
  { code: "MH", name_ar: "جزر مارشال", name_en: "Marshall Islands" },
  { code: "FM", name_ar: "ميكرونيزيا", name_en: "Micronesia" },
  { code: "NR", name_ar: "ناورو", name_en: "Nauru" },
  { code: "TV", name_ar: "توفالو", name_en: "Tuvalu" },
];
