/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTrialBalanceRouteImport } from './routes/_authenticated.trial-balance'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated.setup'
import { Route as AuthenticatedPartnersRouteImport } from './routes/_authenticated.partners'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedAccountsRouteImport } from './routes/_authenticated.accounts'
import { Route as AuthenticatedJournalEntriesIndexRouteImport } from './routes/_authenticated.journal-entries.index'
import { Route as AuthenticatedJournalEntriesNewRouteImport } from './routes/_authenticated.journal-entries.new'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrialBalanceRoute =
  AuthenticatedTrialBalanceRouteImport.update({
    id: '/trial-balance',
    path: '/trial-balance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPartnersRoute = AuthenticatedPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountsRoute = AuthenticatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJournalEntriesIndexRoute =
  AuthenticatedJournalEntriesIndexRouteImport.update({
    id: '/journal-entries/',
    path: '/journal-entries/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJournalEntriesNewRoute =
  AuthenticatedJournalEntriesNewRouteImport.update({
    id: '/journal-entries/new',
    path: '/journal-entries/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/trial-balance': typeof AuthenticatedTrialBalanceRoute
  '/journal-entries/new': typeof AuthenticatedJournalEntriesNewRoute
  '/journal-entries/': typeof AuthenticatedJournalEntriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AuthenticatedAccountsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/trial-balance': typeof AuthenticatedTrialBalanceRoute
  '/journal-entries/new': typeof AuthenticatedJournalEntriesNewRoute
  '/journal-entries': typeof AuthenticatedJournalEntriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/accounts': typeof AuthenticatedAccountsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/partners': typeof AuthenticatedPartnersRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/trial-balance': typeof AuthenticatedTrialBalanceRoute
  '/_authenticated/journal-entries/new': typeof AuthenticatedJournalEntriesNewRoute
  '/_authenticated/journal-entries/': typeof AuthenticatedJournalEntriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accounts'
    | '/dashboard'
    | '/partners'
    | '/setup'
    | '/trial-balance'
    | '/journal-entries/new'
    | '/journal-entries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/accounts'
    | '/dashboard'
    | '/partners'
    | '/setup'
    | '/trial-balance'
    | '/journal-entries/new'
    | '/journal-entries'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/accounts'
    | '/_authenticated/dashboard'
    | '/_authenticated/partners'
    | '/_authenticated/setup'
    | '/_authenticated/trial-balance'
    | '/_authenticated/journal-entries/new'
    | '/_authenticated/journal-entries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trial-balance': {
      id: '/_authenticated/trial-balance'
      path: '/trial-balance'
      fullPath: '/trial-balance'
      preLoaderRoute: typeof AuthenticatedTrialBalanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/partners': {
      id: '/_authenticated/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AuthenticatedPartnersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/accounts': {
      id: '/_authenticated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthenticatedAccountsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journal-entries/': {
      id: '/_authenticated/journal-entries/'
      path: '/journal-entries'
      fullPath: '/journal-entries/'
      preLoaderRoute: typeof AuthenticatedJournalEntriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/journal-entries/new': {
      id: '/_authenticated/journal-entries/new'
      path: '/journal-entries/new'
      fullPath: '/journal-entries/new'
      preLoaderRoute: typeof AuthenticatedJournalEntriesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountsRoute: typeof AuthenticatedAccountsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPartnersRoute: typeof AuthenticatedPartnersRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedTrialBalanceRoute: typeof AuthenticatedTrialBalanceRoute
  AuthenticatedJournalEntriesNewRoute: typeof AuthenticatedJournalEntriesNewRoute
  AuthenticatedJournalEntriesIndexRoute: typeof AuthenticatedJournalEntriesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountsRoute: AuthenticatedAccountsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPartnersRoute: AuthenticatedPartnersRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedTrialBalanceRoute: AuthenticatedTrialBalanceRoute,
  AuthenticatedJournalEntriesNewRoute: AuthenticatedJournalEntriesNewRoute,
  AuthenticatedJournalEntriesIndexRoute: AuthenticatedJournalEntriesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
